### ISSUE TITLE
Consecutive sequences: a streak

### ISSUE THREAD

**Issue by mcostalba** [mcostalba/scoutfish#10]
This is another powerful concept that merges the _sequence_ concept with the _persistence_ concept.

Mainly a **streak** is like a sequence but with added constrain that the conditions should be satisfied one-by-one along consecutive moves.

You may want to use a streak, for instance, to look for a pawn-down imbalance: we need the imbalance to persist for at least few moves to be sure we are not in the middle of a capture-recapture combination.

Indeed the concept is much more powerful and general than simple imbalance, so I'd expect to find other uses in the future.

**Comment by sshivaji** [comment]
This indeed can be interesting! From a chess perspective, i can think of clearance sacrifice in th Benoni for white.

1. Plan of e5, dxe5, followed by f5 and then Ne4 for white. The first three moves are in a sequence, but the last move might be delayed by a move (but is also played immediately).

2. This also covers the plan thing well.

Can we relax the contraint from one move to more?

**Comment by mcostalba** [comment]
Sure, can you post the pgn of an example game with this pattern, so I can
test on it.

**Comment by sshivaji** [comment]
Sure, here is an example PGN which exactly has e5, dxe5, f5 and one move delay followed by Ne4.

The sequence starts on move 19

[Event "Leipzig Olympiad Fin"]
[Site "Leipzig GDR"]
[Date "1960.11.08"]
[EventDate "?"]
[Round "11"]
[Result "1-0"]
[White "Jonathan Penrose"]
[Black "Mikhail Tal"]
[ECO "A65"]
[WhiteElo "?"]
[BlackElo "?"]
[PlyCount "77"]

1.d4 Nf6 2.c4 e6 3.Nc3 c5 4.d5 exd5 5.cxd5 d6 6.e4 g6 7.Bd3
Bg7 8.Nge2 O-O 9.O-O a6 10.a4 Qc7 11.h3 Nbd7 12.f4 Re8 13.Ng3
c4 14.Bc2 Nc5 15.Qf3 Nfd7 16.Be3 b5 17.axb5 Rb8 18.Qf2 axb5
19.e5 dxe5 20.f5 Bb7 21.Rad1 Ba8 22.Nce4 Na4 23.Bxa4 bxa4
24.fxg6 fxg6 25.Qf7+ Kh8 26.Nc5 Qa7 27.Qxd7 Qxd7 28.Nxd7 Rxb2
29.Nb6 Rb3 30.Nxc4 Rd8 31.d6 Rc3 32.Rc1 Rxc1 33.Rxc1 Bd5
34.Nb6 Bb3 35.Ne4 h6 36.d7 Bf8 37.Rc8 Be7 38.Bc5 Bh4 39.g3 1-0

**Comment by mcostalba** [comment]
This is a complex query, but now it works. Query is:

```
{ "sequence": [ { "sub-fen": "rnbqkb1r/pp1p1ppp/4pn2/2pP4/2P5/2N5/PP2PPPP/R1BQKBNR"},
                { "streak": [ { "sub-fen": "1rb1r1k1/2qn1pbp/3p2p1/1pnPP3/2p2P2/2N1B1NP/1PB2QP1/R4RK1"},
                              { "sub-fen": "1rb1r1k1/2qn1pbp/6p1/1pnPp3/2p2P2/2N1B1NP/1PB2QP1/R4RK1"},
                              { "sub-fen": "1rb1r1k1/2qn1pbp/6p1/1pnPpP2/2p5/2N1B1NP/1PB2QP1/R4RK1"} ] },
                { "sub-fen": "br2r1k1/2qn1pbp/6p1/1pnPpP2/2p1N3/4B1NP/1PB2QP1/3R1RK1" } ] }
```

The first subfen identifies the Benoni, then we have a streak with e5, dxe5, f5 and finally, out of the streak, we have the condition for Ne4.

Indeed I have used the full fen from the PGN game, it should work also with the subfen with just the sensible squares set.

**Comment by mcostalba** [comment]
Well, above solution is not correct because it does not considers the dynamic of the moves, but only static positions, so that if in a game the knight was in Ne4 since the beginning, the query would have picked that too, probably not what we want.

This is a deep inconsistency, so I have added the "move" rule, and now the following query is now correct:

```
{ "sequence": [ { "sub-fen": "rnbqkb1r/pp1p1ppp/4pn2/2pP4/2P5/2N5/PP2PPPP/R1BQKBNR"},
                { "streak": [ { "white-move": "e5"}, { "black-move": "dxe5"}, { "white-move": "f5"} ] },
                { "white-move": "Ne4"} ] }
```

BTW it is also much easier to read...

**Comment by mcostalba** [comment]
Done.
