### ISSUE TITLE
Make a python extension for scoutfish

### ISSUE THREAD

**Issue by sshivaji** [mcostalba/scoutfish#13]
While this is not strictly necessary, it makes it easy to integrate into python apps. I have contributed to a python module of stockfish at https://github.com/jromang/Stockfish/blob/pyfish/src/pyfish.cpp (the work was started by Jean-Francois).

I tried to create one for scoutfish but its turns out starting the multi-threaded scout search with listeners is a little more tricky than I expected. However, I think its quite do-able.

**Comment by mcostalba** [comment]
I use pexpect, see test.py

**Comment by sshivaji** [comment]
I saw that of course. A full Python extension is a bit more complex, it requires C++ code in an interface file like the pyfish.cpp above. The benefit is that you can import the project easily in regular python via api like:

import scoutfish
results = scoutfish.scout('<json expression>')

This is instead of using the command line. The disadvantage is the complexity of writing the C++ code, the advantage is the more seamless integration.

If this seems a bit hard for now, we can revisit this later.

**Comment by mcostalba** [comment]
Sorry, I have no experience with this, but I will give it a look.

**Comment by mcostalba** [comment]
Maybe we can start with a simple scoutfish.py file and when API is stable
we can libify it.

**Comment by sshivaji** [comment]
I gave it a try but failed narrowly. I also realized the main reasons for wanting this were:

1. Wanting to process large Json easily from python
2. Set multi threads easily without using an input and output Popen buffer.

Maybe for now, can just use popen, pexpect and can support offset for json

**Comment by sshivaji** [comment]
I mean for now, the popen based scoutfish.py is good enough with max matches support

**Comment by mcostalba** [comment]
After @gbtami patch to use PopenSpawn now this is incredibly fast, don't know what's happened, but now running test.py is almost immediate...

**Comment by sshivaji** [comment]
Great to hear! I think I should be able to fully integrate scoutfish on github.com/sshivaji/Chessui soon in light of the module.
