### ISSUE TITLE
"x86_64" & "x86-64" problem with Makefile

### ISSUE THREAD

**Issue by LocutusOfPenguin** [mcostalba/scoutfish#15]
Hi,

when i try to compile it on my Ubuntu 16.04/x86_64 system, i get make errors.
I had to change the Makefile abit (see title with "-" & "_") to make it work.
see here:
[Makefile.txt](https://github.com/mcostalba/scoutfish/files/645763/Makefile.txt)

Can y take a look?
Jürgen

**Comment by LocutusOfPenguin** [comment]
sorry another error:

./scoutfish scout pgn/electronic_campfire.bin { "sub-fen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR" }
terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected 's'; expected string literal

no matter what ".bin" i try (from the provided examples) or the fen string..i always get this error.

**Comment by gbtami** [comment]
Try with quoting json param:
./scoutfish scout pgn/electronic_campfire.bin '{ "sub-fen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR" }'

**Comment by gbtami** [comment]
@LocutusOfPenguin compiling works for me on Ubuntu 16.04 with:
make build ARCH=x86-64
or with
make build ARCH=x86-64-modern

**Comment by LocutusOfPenguin** [comment]
Hmmm, the compile now works (stupid me?)
Also this quote helps.

THANKS & close.

**Comment by mcostalba** [comment]
@LocutusOfPenguin I have just added a python file called scoutfish.py, maybe it is handier for you to open python terminal, import the Scoutfish class with

`from scoutfish import Scoutfish`

And run queries form there....it is easier to build queries and you don't need to escape quotes :-)

See test.py for an example of usage.

**Comment by LocutusOfPenguin** [comment]
for the quote  ... i copied this from yr README.md :-)
Its perhaps a good idea to update this.

shiv pinged me to take a look in this project (for the UI stuff) - he is prob. interested in this python connection too.
