### ISSUE TITLE
Incorporate chess_db functionality into scoutfish

### ISSUE THREAD

**Issue by gbtami** [mcostalba/scoutfish#19]
From GUI development point of view it would be convenient to have the book/find functionality of chess_db in scoutfish/csoutfish.py. Both using the same parser so this seems reasonable anyhow.

**Comment by mcostalba** [comment]
In my mind I prefer to keep them disjoint. It is up to the GUI to bundle them, possibly together with other sources and databases and provide a consistent experience to the user.

I think every tool should be focused and specific to do one single task. These are back-end tools, not front-end and this is an important difference also from the point of view of the feature set.

I am against a swiss-army-knife approach for a back-end specific tool.

**Comment by gbtami** [comment]
Np, I understand your point.
