### ISSUE TITLE
Max Matches not working in python api

### ISSUE THREAD

**Issue by sshivaji** [mcostalba/scoutfish#20]
I tried 
`    p.setoption('Max Matches', 1)
`

in front of 
```

    for e in QUERY_DB:
        sys.stdout.write('Query ' + str(cnt) + '...')
        sys.stdout.flush()
        result = p.scout(e['q'])
        if (result['match count'] == e['matches']):
            print('OK')
        else:
            print('FAIL')
        p.before = ''
        cnt += 1
```

in test.py and it still works well. Its possible I have something else wrong in my env.

**Comment by mcostalba** [comment]
Can you please post all your script?

**Comment by sshivaji** [comment]
It now works after exactly following the example syntax on Readme.md!

I think offset logic for get_games might be a bit off as the offset now points to the end of the previous game (this is quite convenient as we dont have to do a backwards seek), however scoutfish.get_games(self, list) will probably have to change to break only on the second "[Event" in line occurence. Anyway, I will open a detailed issue or patch later today. Glad that the api now works!

**Comment by mcostalba** [comment]
@sshivaji it already does this, due to the second term in the condition:

`if "[Event" in line and game.strip():
`

**Comment by sshivaji** [comment]
Good point, missed that!
