### ISSUE TITLE
Proposal for UI for scoutfish

### ISSUE THREAD

**Issue by sshivaji** [mcostalba/scoutfish#21]
This might be off-topic for this project but I think its very useful to think of integration even on the backend.

I now think a board editor like https://en.lichess.org/editor is handy. Its not too hard to integrate but I was thinking of a good user experience.

If you right click on a square, note that a circle is drawn, and if you drag while right clicking you can form arrows. The board is also editable. I wonder if queries should be written leveraging this interface code with text boxes for more input such as result, side to move, material, all being dropdowns.

We can use multiple editable boards for sequence search. Wondering if this makes sense.

**Comment by mcostalba** [comment]
Your project https://github.com/sshivaji/chessui seems to me the best place where to work on this integration. If you are willing, I can open some issues there regarding this topic. I have some ideas on how to do it. 

The central point of the user experience in my view is **the game**.

A simple board editor is not enough an is not the good starting point. A real pgn game is.

The user will follow an already open game in PGN that he wants to study. Browsing through the moves he reach a position interesting for him. At that point he may select few pieces forming a pattern (defining a subfen and "adding to the cart", or taking a snapshot), or he may select a combination of moves (defining a moves's streak and add to the cart) and so on (I have in mind many intuitive actions to visually define the single conditions), he can continue through the game and add another pattern snapshot and so on. When he is ready he will issue the built-up query, get results, select one game and start from there in an iterative/cycling process.

In my view browsing the game -> snapshotting/adding to cart query terms -> issue the query and getting new games -> browsing from there are part of a tight iterative and endless cycle that is the user experience I have in mind.

So a UI that supports browsing through a game is a requirement IMO.

I don't know which are your plans with chessui, but in case you are willing to work on it, then this is definitely the way to go IMO.

**Comment by sshivaji** [comment]
Of course, please open issues at https://github.com/sshivaji/chessui 

There are a few other devs also interested in helping.

I was thinking of a board editor as a setup board for quick start, but your ideas seem much more interesting, the add to cart sounds creative and hilarious! Quite impressed by your ideas here, I expected you to be more focused on the hardcore C++ coding.

Will close this issue and resume from there. I will attempt a quick early integration. We definitely want chessui to get the best of scoutfish and chess_db.

**Comment by gbtami** [comment]
PyChess hes some experimental and partial chess_db/scoutfish integration. See https://github.com/pychess/pychess/issues/1406
Any ideas on how to improve it and how to create scout query on GUI are welcome!

**Comment by gbtami** [comment]
Added new dialog to create scoutfish queries: https://github.com/pychess/pychess/issues/1406
