### ISSUE TITLE
Scoutfish crash on .pgn file containing variant games

### ISSUE THREAD

**Issue by gbtami** [mcostalba/scoutfish#23]
I'v tried to find something in my own (lichess) games .pgn downloaded before, but failed because it contained some crazyhouse games. It would be good to support chess variants played on fics/lichess. In theory this would be doable using lichess stockfish variant fork https://github.com/niklasf/Stockfish. If this need to much work maybe just ignore games containing "Variant" tag in .pgn headers.
(Same issue stands for chess_db.)

**Comment by mcostalba** [comment]
Yes, you have a point. Variant are not supported and the parser should skip them.

**Comment by mcostalba** [comment]
Can you please post a pgn file with variants, so I can verify the fix

**Comment by gbtami** [comment]
Unfortunately lichess added variant tags to standard games also. Maybe they will fix this later if they will re enable .pgn download again. (now it's disabled)
[lichess_gbtami_2016-11-16.zip](https://github.com/mcostalba/scoutfish/files/651760/lichess_gbtami_2016-11-16.zip)

**Comment by mcostalba** [comment]
@gbtami it should be fixed in chess_db now, can you please verify if it works for you?

**Comment by gbtami** [comment]
It segfaults for me on lichess .pgn attached above.

**Comment by mcostalba** [comment]
Indeed it was quite tricky to skip to next game in case of a variant is found, for instance we had null terminators '\0' inside teh file so that strstr() failed loudly!

Now chess_db it works for me, can you please confirm? After that I will backport to scoutfish

**Comment by gbtami** [comment]
Yes, it's Ok now. Thx!
