### ISSUE TITLE
Support backend pagination of scoutfish results

### ISSUE THREAD

**Issue by sshivaji** [mcostalba/scoutfish#24]
Right now, we can limit the number of matches, which is great. Ideally, we need pagination of results too. This allows natural exploration with the UI.

Typically, backend code can support a combination of results per page and page number.

Example : if u have 100 results. I want 20 results per page, and give me page 5, should give me matches 80-100. A query of 10 results per page and for page 3, should return matches 20-30.

More details are here: https://www.dynatable.com/#paginating

**Comment by mcostalba** [comment]
I'd guess this kind of pagination is more up to the higher level tool, indeed also dyantable, referred by you, is a client side tool.

In case a real need arises we can of course evaluate implementing something at low level, but at the moment it would seem to me just a "solution looking for a problem".

**Comment by gbtami** [comment]
The real need is the following. If you set Max Matches option to 100 but scouting will find 102 matches the user can never explore the latest two now.

You can see this feature in most SQL/NOSQL databases.
https://www.sqlite.org/lang_select.html#limitoffset
https://www.postgresql.org/docs/current/static/queries-limit.html
http://developer.couchbase.com/documentation/server/current/n1ql/n1ql-language-reference/offset.html
https://docs.mongodb.com/manual/reference/method/cursor.skip/

I think implementing something like "skip" in mongodb would be very useful in both scoutfish and chess_db. Using this feature UI developers can implement pagination.

**Comment by mcostalba** [comment]
@gbtami thanks for point out the links above.

Indeed the standard SQL way is to use LIMIT and OFFSET. Mongo DB skip() is similar but operates on cursors (that are a more difficult concept to implement because are not stateless).

Eventually we can settle on LIMIT and OFFSET. This would require a API change because the parameters are more linked to the query than to the connection (as is 'Max Matches' now).

Indeed the standard SQL way is to use LIMIT and OFFSET. Mongo DB skip() is similar but operates on cursors (that are a more difficult concept to implement because are not stateless).

Eventually we can settle on LIMIT and OFFSET. This would require a API change because those  parameters are more linked to the query than to the connection (as is now "Max Matches")

**Comment by gbtami** [comment]
I think we can use "Max Matches" UCI option as is now to mimic "LIMIT". Adding "skip #" as additional parameter to "scout" command to simply ignore first # matches would be enough to implement pagination in UI.

**Comment by sshivaji** [comment]
Great discussion. We also need total number of matches.

A few points to add from a "UI" perspective. Currently chessui is written in HTML/CSS/Javascript (leveraging bootstrap), this makes calls to python for scoutfish api, python then calls C++.

1. For many matches (>1M), python will be relatively slow (to parse the JSON). Would it be possible to return the number of total matches but only return max_matches if "skip" is not provided?

2. Then we have the number of total matches, lets say 1M, we can then traverse it one page at a time by issuing:
2.1. [limit_max_matches 10] (this query will also get the total number of matches -> 1M 
2.2. [skip 10, limit_max_matches 10] 
2.3. and for next page [skip 20, limit_max_matches 10] and so on..

**Comment by sshivaji** [comment]
Also for chess_db, its enough to do this pagination only for the game_offsets as the rest of the information is already presented in aggregated form (ie total games, and all moves).

**Comment by mcostalba** [comment]
I think  LIMIT and OFFSET or "Max Matches" and skip as suggested by @gbtami are the way to go, reporting total matches requires a full scan and is slower. I don't see it as strictly needed, is more cosmetic than anything else.

**Comment by sshivaji** [comment]
The only benefit of total matches is that the user knows whether the query
given is too broad and needs to be refined. If this is not supported, I can
do a background full scan to display the same results, but this might be
slow.

The alternative is that I can multiply the results returned with limit and
offset and give an approximate total record count, which is probably
sufficient for now.

**Comment by mcostalba** [comment]
@sshivaji returning a % of total file scanned is doable and should give some hint. For instance if you asked for 100 results and scoutfish finds them scanning just 1% of the file, then you can assume we can expect around 100*100 = 10.000 matches.

**Comment by sshivaji** [comment]
That would be great! Then we can cover for speed and the user experience.

**Comment by mcostalba** [comment]
Done.

Returning a % of total file scanned is tricky with multi-thread and an immediate solution is not clear to me. eventually reopen a speciifc issue.

**Comment by sshivaji** [comment]
Can assumption be made that local % of file in thread * number of threads = approximate total % of file that is scanned?
