### ISSUE TITLE
Support "add" another .pgn to existing .pgn/.scout database

### ISSUE THREAD

**Issue by gbtami** [mcostalba/scoutfish#28]
In #8 you wrote "in Scoutfish format you don't need to rewrite the bin if you add/delete/modify some game. In case of add some new games you can just append related info to the bin (almost instantaneous)."
It would be good to have some format of "add" or "append" command besides "make" in scoutfish to append new games to database.

**Comment by gbtami** [comment]
Two use cases of this feature from PyChess GUI is 1. auto save played games and 2. regular (per week) updating of my huge/reference database from http://theweekinchess.com/twic

One can say that auto saved .pgn will never be big enough to be a problem but nothing can prevent users to select f.e. millionbase.pgn as auto save target in preferences menu. In this case and with auto save option checked in this feature can help updating .pgn and .scout  files quickly. (Unfortunately updating chess_db .bin will be a remaining problem, but that is another issue.)

**Comment by gbtami** [comment]
Maybe this can be a bit simpler, just adding one game at a time with something like:
scoutfish append my.pgn {'game': '[Event "?"] ... 1.e4 Nf6 *'}

**Comment by mcostalba** [comment]
@gbtami I'd prefer to delay this wen we will need it for real. I am not comfortable to add features against a  possible theoretical scenario.

**Comment by gbtami** [comment]
This is not just a theoretical scenario. PyChess have to recreate .scout after importing latest twic pgn to current opened .pgn database.

**Comment by mcostalba** [comment]
The point is that this feature is just a speed optimization compared to recreate the full DB. So it makes sense to add this code if the speed up is sensible **and** the DB rebuilding is very slow. Otherwise this feature makes no sense.

**Comment by gbtami** [comment]
Agreed. The question what is the threshold of "very slow". On my Lenovo T510 rebuilding millionbase.scout feels "very slow" for _me_. Of course anyone can say this is fast enough but as a GUI developer I think if there is a solution in milliseconds why not go for it? 

```
Processing...done
{
    "Games": 2201652,
    "Moves": 170110381,
    "Incorrect moves": 0,
    "Games/second": 38571,
    "Moves/second": 2980209,
    "MBytes/second": 25.8772,
    "DB file": "millionbase-2.22.scout",
    "DB file size": 366634622,
    "Processing time (ms)": 57080
}
```

**Comment by mcostalba** [comment]
Whai is sensible is the usage scenario: IMO your really don't want to update the big DB after each game. Do you want to do this?

**Comment by gbtami** [comment]
I'm talking about updating a big db from http://theweekinchess.com/twic regularly here. But importing(appending) any .pgn to a big db in general raises the same problem. (PyChess supports "Import" in database menu.)
 To summarize my problem a .pgn database (and _any_ database) in general have to support add/delete/edit scenarios. This is not a problem with .pgn but may be slow in GUI if .scout can be extended with regenerating it only.

**Comment by mcostalba** [comment]
@gbtami  see the log message of https://github.com/mcostalba/scoutfish/commit/00cec1339f97114a32c30080dbad5e3a500634f2. It should fix the issue for you. Can you please verify? Thanks.

**Comment by gbtami** [comment]
Works like charm, thx!
