### ISSUE TITLE
Encode Result value

### ISSUE THREAD

**Issue by sshivaji** [mcostalba/scoutfish#3]
It might make sense to encode the result value so that we can answer questions like whats the value of 2 Bishops vs Bishop and Knight in open positions and how about closed positions (its an interesting sub-topic to think about how to represent open and close positions, I will start a separate issue on that).

If we encode result, we can answer those queries easily. Like 2 bishops vs Bishop and Knight is worth half a pawn (Kaufman thinks its half a pawn in his books) in the middle/endgame.

**Comment by mcostalba** [comment]
Done.
