### ISSUE TITLE
Scoutfish raises EOF expection

### ISSUE THREAD

**Issue by gbtami** [mcostalba/scoutfish#30]
I get EOF exception with attached pychess.pgn

tamas@tami:~$ PYTHONPATH=pychess/lib python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pychess.external.scoutfish import Scoutfish
>>> s=Scoutfish(engine="pychess/lib/pychess/external/scoutfish")
>>> s.open("./pychess.pgn")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tamas/pychess/lib/pychess/external/scoutfish.py", line 32, in open
    self.db = self.make()
  File "/home/tamas/pychess/lib/pychess/external/scoutfish.py", line 48, in make
    self.wait_ready()
  File "/home/tamas/pychess/lib/pychess/external/scoutfish.py", line 23, in wait_ready
    self.p.expect(u'readyok')
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF).
<pexpect.popen_spawn.PopenSpawn object at 0x7fd774d5d1d0>
searcher: searcher_re:
    0: re.compile("readyok")
>>> 
[pychess.zip](https://github.com/mcostalba/scoutfish/files/669166/pychess.zip)

**Comment by sshivaji** [comment]
This might be because of the timeout in scoutfish pexpect python wrapper.

**Comment by gbtami** [comment]
I don't think so. It produces segfault from command line with: scoutfish make pychess.pgn
I'm afraid it contains a variant game without "Variant" tag or just a game with invalid move causing the segfault. I will try to find it later.

**Comment by mcostalba** [comment]
@gbtami please try to parse that file directly from the native C++ tool, so you will get some hint more.

**Comment by mcostalba** [comment]
File pychess.pgn still fails because it is full of garbage FEN like this:

[Event "Helyi esem�ny"]
[Site "Helyben"]
[Date "2015.11.06"]
[Round "1"]
[White "tamas"]
[Black "Vend�g"]
[Result "*"]
[Time "18:19:00"]
[SetUp "1"]
[FEN "k1K1k2r/2R5/8/8/8/8/8/8 b KQkq - 1 2"]
[PlyCount "0"]

 *

But I really don't care about broken FEN!

**Comment by gbtami** [comment]
I'm really sorry wasting your time with my own pychess autosave .pgn. I think these games was saved when I was implementing "Setup Position" and pychess doesn't validate FEN.
Thx for investigating anyhow!
