### ISSUE TITLE
stockfish code

### ISSUE THREAD

**Issue by lucasart** [mcostalba/scoutfish#32]
more of a question than an issue. why does scoutfish embark the whole stockfish code? based on the readme and python wrapper, i don't understand why you need all the search and syzygy code. is there some kind of undocumented feature where this is useful ?

**Comment by mcostalba** [comment]
@lucasart with chess_db I have removed all unneeded SF code, just to find myself that I had to readd some bits. Here I prefer to leave that in, as long as the code base is stable enough and proved on the field by some working GUI, just to avoid me to readd stuff...
