### ISSUE TITLE
Mate, stalemate

### ISSUE THREAD

**Issue by gbtami** [mcostalba/scoutfish#34]
I don't know stockfish internals but new position rules like "mate" and "stalemate" can be useful too if it's possible. Maybe the best would be to expose _all_ chess knowledge stockfish has in a particular position.

**Comment by mcostalba** [comment]
@gbtami is this functionality something you use somewhere? Can you please point me to your use case?

**Comment by gbtami** [comment]
When you teach chess for kids usually you prepare to show a new topic. Say I like to find some real life games ending with a given mating pattern. I can scout for "sub-fen" now, but most of the resulting games are not mate because the checking piece can be captured.

**Comment by mcostalba** [comment]
Added, see ac97e91c4c0c56ac

**Comment by gbtami** [comment]
Great, thx!
