### ISSUE TITLE
Test case question

### ISSUE THREAD

**Issue by gbtami** [mcostalba/scoutfish#36]
What is https://github.com/mcostalba/scoutfish/blob/master/src/test.py#L48 test good for?
Why is it a "streak" and why it contains 2 "result" rule?

**Comment by mcostalba** [comment]
It is used to verify it return 0, as expected. Results have a different logic from remaing rules, when a result does not match, parser skips the game, so I wanted to verify if this is caught correctly even with a streak.

**Comment by gbtami** [comment]
I see now, thx!
