### ISSUE TITLE
"exact-fen"

### ISSUE THREAD

**Issue by gbtami** [mcostalba/scoutfish#39]
README.md say that full FEN is just a special sub-fen. It's only true in the early phase of games. Later especially in end game phase a given sub-fen can match to several game positions with additional pieces in squares where sub-fen contains "8". Of course exact FEN can be expressed using one "sub-fen" _and_ one "material" rule, but it would be more convenient to use "exact-fen" only. What do you think?

**Comment by mcostalba** [comment]
I prefer to avoid introducing redundancies for the moment and keep it as orthogonal as possible. So I think sub-fen + material, as you pointed out, is the correct way to go. Eventually I can document it in README
