### ISSUE TITLE
Mobility support in queries

### ISSUE THREAD

**Issue by sshivaji** [mcostalba/scoutfish#4]
Does it make sense to add mobility support? This allows us to query on "open" or close positions. One simple metric is if there are many legal moves, its an open position, in a closed position, the number of legal moves is restricted.

Whats the best construct to reuse from stockfish? For human players, they typically differentiate, open, closed, semi-open, and semi-closed positions. Semi-open and semi-closed are usually only in the opening.

Can we have something like 1-5 for mobility, where 5 means very open positions and 1 means very closed positions?

**Comment by mcostalba** [comment]
This heuristic is not good, I can tell you with confidence as engine developer. Indeed detect closed positions is still an open issue in engine development.

**Comment by sshivaji** [comment]
What kind of scale do you normally have for mobility? Maybe we can use that scale.

**Comment by sshivaji** [comment]
A more refined idea that is generic as well. Can we simply support number of legal moves in a query (can also be a range query)?

**Comment by mcostalba** [comment]
This would greatly slow down the search for very little added value.

Fast search is the real trademark of the tool and should be preserved.

**Comment by sshivaji** [comment]
I see. Good point!

Alternate idea. I think there might be a simple way of indicating closed position by pawn structure in sub-fen search. Typically closed positions have pawn chains that are opposing each other:

French: white pawns on d4 and e5 opposed by black pawns on d5 and e6.
Kings Indian: white pawns on c4, d5 and e4 opposed by black pawns on d6, and e5.

Do you think that can simply be expressed in a sub-fen search (the concept of opposing pawns).

**Comment by mcostalba** [comment]
Yes of course.

**Comment by sshivaji** [comment]
Ic, then the more matches of directly opposing pawns, the more closed a position typically is. What we have now is a good starting point!

Later, maybe it makes sense to add support for number of sub-fen matches in a position (or something similar) and sort by that number? Then we can get "super" closed positions first followed by less closed positions. Anyway, just an idea..

**Comment by mcostalba** [comment]
For the moment sub-fen with pawn structure seems the way to go. I am closing it, eventually it could be reopen in the future but with something more specific.

On this project I am not nitpicking on the issues like for SF, but anyhow open issues should be quite up to the point and specific to keep them sensible.

**Comment by sshivaji** [comment]
I forgot to close issue. I will open an issue later on ranking matches. For the sub-fen with pawn structure match, I wanted to sort reults by the number of matches in a game. I will open a specific issue after trying this query out.

**Comment by mcostalba** [comment]
@sshivaji well, the search stops at first match. To continue till the end slows down the tool and I am not sure I understand the added value: what is the reason to sort them out?

Anyhow, this tool does not aim to replace a full UI, this is just the back processor, but you may want to use a higher level tool, both for composing the query (for instance out of a point and click web interface) and properly report query results, eventually picking up the matched pgn games from the pgn file. I see your sorting as a post-processing (if you really want to do it) for the UI tool.

**Comment by sshivaji** [comment]
The refinement I am thinking about is how many moves does a pattern exist for in a game. Lets say you are looking for the example of 2 Bishops vs Bishop and Knight. However, you find out that the Bishop swaps itself for a knight in 1 move, then its not an ideal candidate game. Returning how many moves a pattern occurs for is useful.

The other use case I had in mind was lets say you are looking for one pawn opposing another for evidence of a closed position. A position where 3 black pawns oppose 3 white pawns will have more weight that a position where its just 1 vs 1.

Having said this, I will keep testing the tool for UI use. I will start incorporating it very soon and post feedback.
