### ISSUE TITLE
Sequential conditions

### ISSUE THREAD

**Issue by mcostalba** [mcostalba/scoutfish#7]
This is a very powerful concept!

The idea is to allow more than one condition to be valid at different points in the game. For instance we can search for all the games with a given opening (passing the corresponding sub-fen) and that end up with a given material distribution like KNNKB. Note that the 2 conditions are not required to be true at the same move, as is the normal case, just at least once per game, for the game to be selected.

**Comment by sshivaji** [comment]
This is very useful in looking for a piece path from a position. Typical tournament player questions are:

1. How does one maneuver the bishop in this opening, should we go f1-d3-c2 or f1-b5-a4. When should we select which maneuver?

2. What are white's plans and black's counter plans? Which weakening black moves allow best chances for a white plan.

These questions are a bit complex, but starting with sequential conditions would be powerful indeed!

**Comment by mcostalba** [comment]
Done https://github.com/mcostalba/scoutfish/commit/7e2c4c9fa68337ebc907c208830

I have reused your text in the README: it was well explained, hope you don't mind.

**Comment by sshivaji** [comment]
No problem at all! Actually, you are make me feel guilty for not committing and testing enough. I will attempt UI integration soon and report back.
