### ISSUE TITLE
Search for material imbalance

### ISSUE THREAD

**Issue by mcostalba** [mcostalba/scoutfish#9]
Maybe can be useful to search for all the games where one side is 2 pawns down and won, or where we have a BB vs NN endgame.

**Comment by sshivaji** [comment]
Yes, quite useful. I am especially curious on positions where we have a BB vs NN (or even BN) and the side with BB is down a pawn but still won or drew.

**Comment by mcostalba** [comment]
Done. See https://github.com/mcostalba/scoutfish/commit/1e4dd13125c1d3a45059fc2
